### ISSUE TITLE
No thermostat temperatures

### ISSUE THREAD

**Issue by kopanicak** [vogon1/homey-fhem#1]
I use FHEM 5.8 with MAXLAN (with 3 thermostats) and Homey 1.5.11.
In FHEM I set "homeyMapping" on devices.
![02](https://user-images.githubusercontent.com/9351901/43255042-0d389d1a-90c9-11e8-8fa8-5e2be9fc52f4.jpg)
I see these "Readings" in FHEM:
![01](https://user-images.githubusercontent.com/9351901/43255217-873ad9e8-90c9-11e8-8177-4264a0514d70.jpg)
On Homey was pairing OK.
But I can see any temperatures in Homey devices.
![screen1](https://user-images.githubusercontent.com/9351901/43255184-745849d2-90c9-11e8-8330-de7d1d1d5fdd.jpg)

If I set temperature on device in Homey, than in FHEM Event Monitor I can see this log still with value 0.
![03](https://user-images.githubusercontent.com/9351901/43255466-2aedf192-90ca-11e8-8465-1883147d3f76.jpg)

What I do wrong? With witch version of FHEM was communication OK?

thanks for reply

**Comment by vogon1** [comment]
Hi,

Your configuration looks fine.
Do you have other devices that actually work between Homey and FHEM?

Sietse

**Comment by kopanicak** [comment]
Sorry for slow response. I don't know what happend, but in Homey i can now see both actual temperatures of thermostats. Maybe Homey or FHEM restarts helps.
One thing that is still not working, is set desired temperature from Homey. If I set any temperature in Homey, than in FHEM is not changed. 
In FHEM event monitor log are still wrong lines like that:
![logs](https://user-images.githubusercontent.com/9351901/44996227-f84c9300-afa6-11e8-9f3d-593684ab39b0.jpg)
I dont have any other devices in FHEM.
Can I check something to debug this problem? Thanks

**Comment by vogon1** [comment]
Hi,

Do you still have this problem?

**Comment by vogon1** [comment]
Due to no response, I close this issue.
