### ISSUE TITLE
no devices found after 30000ms, app crashes

### ISSUE THREAD

**Issue by mueckehh** [vogon1/homey-fhem#2]
Hi I try to use FHEM with Homey and RaspberryPi to integrate MAX! Cube from EQ3. On the server FHEM 5.9 is up and running and it works fine. All devices are found and I can change the values inside the FHEM user interface. Inside the Homey App no devices are found instead the App crashes (see screen shot below).

<img width="860" alt="Bildschirmfoto 2019-05-01 um 17 42 27" src="https://user-images.githubusercontent.com/50176202/57025848-9da02f80-6c38-11e9-86be-382d022283d1.png">

I added a new attribute as described in your readme:

<img width="860" alt="Bildschirmfoto 2019-05-01 um 17 44 41" src="https://user-images.githubusercontent.com/50176202/57025943-d6400900-6c38-11e9-87c7-2823595dee84.png">

The following error message is shown inside the Homey App:

![IMG_56490128280E-1](https://user-images.githubusercontent.com/50176202/57026047-169f8700-6c39-11e9-8768-3b294f818c2a.jpeg)

I hope you can help me. Thank you in advance

Thomas

**Comment by vogon1** [comment]
Can you check your configuration?
In my case, server is zaphod.vogons.ut, port is 8083, path is /fhem/

Visiting http://zaphod.vogons.ut:8083/fhem/?cmd=jsonlist2 returns a list of devices.
What about your case?

Sietse

**Comment by mueckehh** [comment]
Hi Sietse,

thank you for your quick answer. Interesting: no result is listed, the screen is blank. 

Thomas

Von meinem iPhone gesendet

**Comment by mueckehh** [comment]
Hi Sietse,

since version fhem 5.8 a token must be used. I tried it like it was documented for version 5.8 and 5.9:
pi@raspberrypi:~/.homebridge$ curl --data "fwcsrf=$(curl -s -D - 'http://localho
st:8083/fhem?XHR=1' | awk '/X-FHEM-csrfToken/{print $2}')" http://localhost:8083
/fhem?cmd=jsonlist2

Now I get a long list back.

could it be, that this mechanism must be used inside your App?

here the link to the docs: https://wiki.fhem.de/wiki/CsrfToken-HowTo

Thomas

**Comment by mueckehh** [comment]
Hi, me again, I just check the "homebridge" implementation. There I found the following command:

fetching: http://10.0.1.35:8083/fhem?cmd=jsonlist2%20room=MAX_SF&fwcsrf=csrf_686095238526524&XHR=1

this trust me that your App has to be updated. I hope it is possible to you to make the changes.

thank you in advance Thomas

**Comment by vogon1** [comment]
I have submitted a new version of the FHEM app to the beta channel of Homey. As soon as it gets approved, you should be able to connect to FHEM with the csrf token.

**Comment by vogon1** [comment]
The beta version 0.6.0 is now live @mueckehh can you please test the new version with token enabled in FHEM?

**Comment by mueckehh** [comment]
Hi, thank you so much for your update. I‘m just on a vacation trip. I will test it immediately after my travel back. I hope I can give you a first feedback next weekend. 

Thank you for your Support

Thomas 

Von meinem iPhone gesendet

**Comment by mueckehh** [comment]
Hi, I just tried to install the beta. Sorry, the beta causes issues. I deinstalled the 0.5 Version, than I tried to install the 0.6 Version. The installation finished with error message that my homey is not reachable.  Than I checked the Homey and I saw an installed FHEM 0.6 but the App has crashed. Reset of the App does not work. This is the result of my current testing. 
Thomas

**Comment by mueckehh** [comment]
Additional comment: for me it is not possible to add the ip-address. Save has no effect. Reason could be the App crashes.

**Comment by vogon1** [comment]
@mueckehh My bad - there are missing files in the github repo.
I fixed it, and I am now waiting for Athom to accept the new version.

**Comment by mueckehh** [comment]
Great! Thank you for your quick response.

**Comment by vogon1** [comment]
Version 0.6.1 has been published. Can you try?

Thanks,
Sietse

**Comment by mueckehh** [comment]
Hi, the update works automatically without any error message, this is fixed now. Server IP is now saved within setup. I found some of my resources (currently only some of the temperature devices) by at all other types the 30.000ms error message was send to me.

The UI does not show any temperature and a change of the temperature value causes an error:



At weekend I have more time to investigate…

With regards

Thomas
