### ISSUE TITLE
More sensor data

### ISSUE THREAD

**Issue by tccflash** [vogon1/homey-fhem#3]
Hi,

is there any chance to bring following readings from the sensor to homey:

Raining - yes/no
Wind - in m/s
Sun position - south/west/east
Brightness - in lux (lx)

If it is possible please integrate this.

**Comment by vogon1** [comment]
This will need a new device type (or multiple  device types) in the FHEM homey driver with the needed properties. It can be done. I don't have the time to add this, but I am open for pull requests.

**Comment by tccflash** [comment]
To bad for me... I am a absolute newbie in the Szene. Can you tell me
what's a pull request? What I have to do for this...

Sorry if this is a dump question.

Greatings

Sietse Visser <notifications@github.com> schrieb am So., 25. Aug. 2019,
21:56:
