### ISSUE TITLE
Lost Connection to FHEM server

### ISSUE THREAD

**Issue by tccflash** [vogon1/homey-fhem#5]
Hi...
After the update to Homey FW 3.1.0 and the new app Update the FHEM app lost connection to the FHEM server. 
First a error appears that the FHEM App stop working. Than in the config the IP Address is lost. After a app reboot the app works for 10 min. Than the same Problem. 
Can you please take a look if you can fix it?

**Comment by tccflash** [comment]
> Hi...
> After the update to Homey FW 3.1.0 and the new app Update the FHEM app lost connection to the FHEM server.
> First a error appears that the FHEM App stop working. Than in the config the IP Address is lost. After a app reboot the app works for 10 min. Than the same Problem.
> Can you please take a look if you can fix it?

I can see in the report, that the app have a problem to get the device tribers.

**Comment by vogon1** [comment]
I am still on Homey 2.x and I don't feel like upgrading yet, so I cannot reproduce the problem.
Did you install the FHEM app via command line tools? If so, you can see the console output of FHEM, maybe that helps.

**Comment by tccflash** [comment]
Yes I installed it per CLI too... There it said that its a problem to load the drivers from fhem.

**Comment by vogon1** [comment]
Can you cut/paste the message?

**Comment by tccflash** [comment]
I will have a look later when I am at home. Actually I have reinstalled the App from the new App store and it runs still for 30min. I will report you later... Thx for the quick answer on this point!

**Comment by tccflash** [comment]
Hi Vogon1.
The App is still running now. It runs on other homeys from other users now still too. I hope/think you can close that issue. 
But I don't understand why these problems where today... Since it is back in the new app store it runs like a charm, but these impossible that this was the problem... However... Thanks for your support und the great app you have created. It is awesome!

**Comment by vogon1** [comment]
Thanks for the report.
I read somewhere that more properties are now stored in Homey about your devices. So maybe the internal ‘upgrade’ of the devices caused the crashes.

Just guessing.

Sietse

**Comment by tccflash** [comment]
That's the only reason with any logic in it! Thx again.
